services:
  odoo:
    image: odoo:17
    container_name: odoo
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: odoo -c /etc/odoo/odoo.conf -i base