version: '3.1'

services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: >
      odoo
      --config=/etc/odoo/odoo.conf
      -d quiz_ht6e
      -i base
